sudo: false
language: node_js
node_js:
- '10'
cache:
  directories:
  - "$HOME/.npm"
branches:
  only:
  - master
  - "/^v\\d+\\./"
script: yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: editied@gmail.com
  on:
    tags: false
    repo: edtoken/clean-typescript-package
env:
  global:
    secure: IoBnC1cMhvl02ddIiGpcOKWuThBCEZrFBYF6XfPwBV5D66ov6AmvbkInKn6Bl/Vi7zOqqNTARsCkopOSOKHgEib2gmhaPo3A55NkKOvgo2XUg5aejRkeH5B0ZmNsBuFYCi+YA7ajZ1dQRQdSaDJsS01h734lWxYuEPRqSBKOdjCxVwRtLTqz1x+gncAhxGvPkaZRCxYnPPMNxjeg9MJfsNLevEJc/Ywk4+5X8H/pWi0pZQfFN0IKpxC4jkyORM4don+jYYCqMU8N776bNkyb/RvQUgNsHUeBQrne2RX6E2sM0rSgItDatrM+hfmlbb0ntBTxdafSH3JAfkmMtRNty73BnDCe4jA38JVkqYIVixL7iRnGCDknRxX5JIAHBkhShr+60ZKfVdFvhesX9mtLsJKiP3wVfSgFmOEwaxCReIxVvcj7GxmhtOuWUtD2kdoIpCR5Rycg3EPcsY0cYQQ0dY7WEsqjnz4AXqjIQtyLh54UFI7zw2TnE43RZ2vXdtUU7yarnmpmaDvZmWzeprSaZjkvTqxDSUMfZvERbfG4xp7OMjizaS0JMWU2ZndwjrAn1+gZiLSIESmRzDWwv0aqZhXC6AtxH5lEWcIJBb0ouMCaTF7LJBNH2x4ycwXLVue/WosBet+9NMXI2tPJ2GWm25oKha1xwMu7Uj/5Cv3apa8=
