sudo: false
language: node_js
node_js:
- '10'
- '8'
cache:
  directories:
  - "$HOME/.npm"
branches:
  only:
  - master
  - "/^v\\d+\\./"
script: yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: editied@gmail.com
  api_key:
    secure: "CJMaI2xOkPqHSHn8+MCfPkzabRV/R0c4ype6uo0G+YwUNrerEUYfGUiSlSNxjwLYbPbOuhPLU5exVQCGjgBm643AeyN2L7LpHPL6/Qn6WLa3Scxi+dikmWgFrYc7Ytdd+npmaccflFsmRhelulw1/dIHDexNl6eYPQkNY2tJQowHbZymhsn18UotnMOb7tSoe7dm/JH1R7JcZBQS0XDvAA95Idoce8xyQgwhP7uuwOh1q3b6hXKBLwNh0i6BEhd3KEAkxcYtaKV46ZSNs7DKhNc4ZNA5c4HZCog4+eXyR37b8AIgfrnfOvEH7AFvzshT+snbHCRhY6RH0RBu1aiw8wPoYbGwBkNWfl2YDqRKLkjs+zlObY+HXXHv3zQ6hHIVviexU06cCAY0oLeuWXlyTaTArlqAJcB4DR5WPNwaQ/xNQ5TwoVEIVr48vZE595wwMTWXzRTqBD6c8QAyzhS2l4JnMPcMc9eGLbaNZ/+3tjRb7sxfEYOMn9JLBT9BNAsQBbpPWuvPg0N52lzb6pwAobbmCXwtDqYO049L/Q7U4K4wWSMIE/WA8RiSl5lXBq4Dsrv7q47pjYQ4kiHJB/uVKJCpPFARThcc02U9MiE5mZ3i2JMVmjqwGFhzcPeKWcuz/lZH7ZDDYVU+S+r1iGvcdElRS6r1PzeHkiTT8gKY3KU="
  on:
    tags: true
    repo: edtoken/clean-typescript-package

