sudo: false
language: node_js
node_js:
- '10'
#- '8'
cache:
  directories:
  - "$HOME/.npm"
branches:
  only:
  - master
  - "/^v\\d+\\./"
script: yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: editied@gmail.com
  api_key:
    secure: pmw3XHieJjL8OoWZAcg0WIauFIngSA9f2Ty2WlEu3HIftdS2mDsLGLK6YyVMcBu8b1XrU297ZYH5M01ay4S2m2CbbEatjNQbN5cK4dOKOBYJhziKiZrPqWO/E+MD1nQHhjezfuneA0yEhwHKK4AuSv9aXhliX+PftJeyFj6kup02F2IF3V/iopNMA9sqKPbvpNsL4k0bgK2b6t67WTfL9S9dBQOPN6HWCKAeD8PHRsgqOXtqFFytYFiWGTeSKncAl5XicIkcVIkBXIukqVZo3Q0kbtJKnLo7DkzpfiT75GTlqA6v1cJfgA6K2pyb8XLpY6vkksq2y13hGZUjvY+2GTDLehMILGSF17fXSMGmnTPBWFAuEApKWORXuvNYhrjoQhrVrhzCrioMFbzaBJZ8ZiC0r4JGSeBTLEwfpANz1r7ukjAeUlv2IAzT4T/fDPZhtTene/3G+F0XjAb1eG0vpiG+Pq1Bm+WpRsLqKw3S4nZjqRglnyADAbmzk6M9LhoLrZZes/G/eFr2eSvbYEJII5T3mCRyL19jpUZMC2YcnhwSqvDqMBvupDZI0DUAjFL+l/qhUqybuQbBR9wXIafp9+VDfrliLsE9ULmKfuPPWxGbIb+KAJQzHOj6hepQ9Y78/9bDNbRfQr9pPNXkdjAlm/a74uCw/vC73s89XPXND4o=
  on:
    tags: false
    repo: edtoken/clean-typescript-package
