sudo: false
language: node_js
node_js:
- '10'
- '8'
cache:
  directories:
  - "$HOME/.npm"
branches:
  only:
  - master
  - "/^v\\d+\\./"
script: yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: editied@gmail.com
  api_key:
    secure: tsTmkPNSaUqOuffwVEFbu+MEpZAGOcFpXlEonF69+Ag/bcmfyB6oTOlqUeF1ySEpgvp/WBbZuXLwwkqWBCpzTs7DF3kf8aSM1Kx//4hfpldz40fBX2m3WvbPFsJLx4UYKqN6HzkymIr4FSiQJ+GXNjjjeKEw54pFGgJsdD9M3r88YSLHK1Ielbq8TTTXiuZN6ba6QWlnF4JxA5D8Nw6pIN78lJb6opewRu8eOc2bNdc8TG2WaNV/A9PYHdj6/wRb/QpYOFhswz9iplcAr/pc7UxGsMvUwwbJ2c6cmTM+pLNvaxzMuO/2TQxfv2Porb3WuODtwp4A5vMJRbjTjtjzOzRtUZwQy0vWMLNIo5iyTws+lGdI0ot6WQRAZLJiLMYwmc4WtrtWqmTwZZFYfZP1g+/RsiiQ4fAiudHSswTDFfczoW71frEBFilEjmQSgvzfIiflRJcTLFLgA4Gx0aKhOid/KuzDgLMVT8J7pc/2QO4YNLNe4DFfrU72LdUr7iNMdlsuy03Ihjktlko2UaS0DEFzLX+ND1shP0xL6hzn8eIpwz4aV9kN/qpLo0IZMUst5l/mmHHlgiLxm+1LCiPbYgY7/7jtliFi7h1M2b2b6CQs+LR0NTeDy4r49SVgR1fRmgZhLpkoxJ03lF7yz/uHrgxR0j/HQMvI7MT+lePg4d0=
  on:
    tags: true
    repo: edtoken/clean-typescript-package
env:
  global:
    secure: tsTmkPNSaUqOuffwVEFbu+MEpZAGOcFpXlEonF69+Ag/bcmfyB6oTOlqUeF1ySEpgvp/WBbZuXLwwkqWBCpzTs7DF3kf8aSM1Kx//4hfpldz40fBX2m3WvbPFsJLx4UYKqN6HzkymIr4FSiQJ+GXNjjjeKEw54pFGgJsdD9M3r88YSLHK1Ielbq8TTTXiuZN6ba6QWlnF4JxA5D8Nw6pIN78lJb6opewRu8eOc2bNdc8TG2WaNV/A9PYHdj6/wRb/QpYOFhswz9iplcAr/pc7UxGsMvUwwbJ2c6cmTM+pLNvaxzMuO/2TQxfv2Porb3WuODtwp4A5vMJRbjTjtjzOzRtUZwQy0vWMLNIo5iyTws+lGdI0ot6WQRAZLJiLMYwmc4WtrtWqmTwZZFYfZP1g+/RsiiQ4fAiudHSswTDFfczoW71frEBFilEjmQSgvzfIiflRJcTLFLgA4Gx0aKhOid/KuzDgLMVT8J7pc/2QO4YNLNe4DFfrU72LdUr7iNMdlsuy03Ihjktlko2UaS0DEFzLX+ND1shP0xL6hzn8eIpwz4aV9kN/qpLo0IZMUst5l/mmHHlgiLxm+1LCiPbYgY7/7jtliFi7h1M2b2b6CQs+LR0NTeDy4r49SVgR1fRmgZhLpkoxJ03lF7yz/uHrgxR0j/HQMvI7MT+lePg4d0=
