sudo: false
language: node_js
node_js:
- '10'
#- '8'
cache:
  directories:
  - "$HOME/.npm"
branches:
  only:
  - master
  - "/^v\\d+\\./"
script: yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: editied@gmail.com
  api_key:
    secure: "pw6XmbqD5FrZpTnn7NNXJpS+1DEx+G1BMtZlVHQyVQX4611JoTkdjT0f3TBFnuCRRm63+VtpE8RYNYf34QH/YTxFr5kh8rGhzskZISO3CpVRC+MEd0gRhBZ1l14V8rtwA9Fx0iuKw+bBaKKO2UVQL9wQ9kbTpOXy0vSQ8gaXbvsgAvTEaJfQa7+LCsw/MCQ/5U2WzWF8KeLEIsM3t2+8rdqNaZi3/Yv3X1sASwK7EBd0vb7Se64rYWDtHa1giaLElVhyERIrowLSvRyEAPQzQHsULJYT957kOxxOhzbdaPWhGepCnoY44NkOAmObNLvskCxuFmNXVFQAkmFydFTBA470beX8fNOxoMeK+Z7cGVy8w2bmUrH6I05C/ApkqZCaOQm/X8pqikxdyfJI64ggbfvgtAUfnWK4NnAtLJ2WrgugG+26BvlBxZM2p2glDYfv/J1aRqb7UQ7PH3vJX6d3LLJKtREFoMhBYr9vGbIYqFuEtoRkRVPYp1GUMdIsgczYmL3kTxJYkTnIoCZhfG8DeLGHdID09mpzglQGKw4iCGc5FLGVxMxhpt1H27NUFAywtiAQTZsLAJTPtN2Je4CGqwAwLJXSh7vgFy2Ms0U8FWfb4gjljJVa5G4GNoB9og+2pY+zhHmD5JTfDD+qnByCTS5xFmB7zU2s8kSQbE5Mvrg="
  on:
    tags: false
    repo: edtoken/clean-typescript-package
